version: "3"

networks:
  net_bet:
    driver: bridge

services:
  db:
    image: "postgres:latest"
    hostname: mysql
    restart: always
    networks:
      - net_bet
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=hero
      - POSTGRES_PASSWORD=hero
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1027:1025 # smtp server
      - 8027:8025 # web ui
  redis:
    image: 'redis:latest'
    ports:
      - '63791:6379'
    networks:
      - net_bet
